### ISSUE TITLE
Update the codebase to use version 2 of the FedEx API

### ISSUE THREAD

**Issue by rmcveigh** [WhatArmy/FedexRest#11]
FedEx has a second version of its API and is starting to drop support for version one. I wonder if we should add a variable to the authorization creation that defines the API version to use. Based on some minimal tests, it looks like this may require a bit of refactoring of the services.

**Comment by code2prog** [comment]
> FedEx has a second version of its API and is starting to drop support for version one. I wonder if we should add a variable to the authorization creation that defines the API version to use. Based on some minimal tests, it looks like this may require a bit of refactoring of the services.

I will watch it in the morning and try to solve the problem

**Comment by code2prog** [comment]
@rmcveigh version switch will be good but i think we should separate codebase in src directory and tests (v1,v2...). What do you think?

**Comment by rmcveigh** [comment]
> @rmcveigh i think we should separate codebase in src directory and tests (v1,v2...). release `0.5.x` will use a version of v1 release `0.6.x` will use a version of v2 What do you think?

I believe it's a great idea. Do you think it's feasible for us to implement a system that enables users to choose the version of the FedEx API they prefer? Or would that make it too complicated?

**Comment by code2prog** [comment]
@rmcveigh  I think there will be no problem with that

**Comment by code2prog** [comment]
@rmcveigh do you known where is documentation for v2 API? I can only see v1 on fedex pages. after changing in api address to v2 I get 404

**Comment by rmcveigh** [comment]
@code2prog, I do not. I discovered they are switching to version 2 after the URL for their shipping labels changed to something like `https://wwwdev.idev.fedex.com/document/v2/document/retrieve/SH,794810209259_SHIPPING_P/isLabel=true&autoPrint=false` The new URL started causing issues with this library when generating shipments because (it looks like) it is expecting a different structure (one with `/v1/`.)

This change on FedEx's part leads me to believe they are moving toward a second version of the API, but maybe they just altered the URL they return for their shipping documents.

**Comment by rmcveigh** [comment]
@code2prog, I do not. I discovered they are switching to version 2 after the URL for their shipping labels changed to something like `https://wwwdev.idev.fedex.com/document/v2/document/retrieve/SH,794810209259_SHIPPING_P/isLabel=true&autoPrint=false` The new URL started causing issues with this library when generating shipments because (it looks like) it is expecting a different structure (one with `/v1/`.)

This change on FedEx's part leads me to believe they are moving toward a second version of the API, but maybe they just altered the URL they returned for their shipping documents.  

The docs are also starting to use the v2 in their URLs. `https://developer.fedex.com/api/en-us/catalog/ship/v2/docs.html`

**Comment by code2prog** [comment]
@rmcveigh its not the case.
When you change doc url to something like this https://developer.fedex.com/api/en-us/catalog/ship/v4/docs.html
v4...9 etc. always show same doc xD Same with tracking etc
WTF? xD

**Comment by rmcveigh** [comment]
Interesting. Well, maybe this issue should be about getting labels from a shipment instead. I'll create a new issue to work off of when I have a moment to do so.
