### ISSUE TITLE
New FedEx Virtualized Sandbox for Testing

### ISSUE THREAD

**Issue by rmcveigh** [WhatArmy/FedexRest#14]
It looks like FedEx has released [a new Virtualized sandbox for tests](https://developer.fedex.com/api/en-us/guides/sandboxvirtualization.html). We should probably consider adjusting the tests in this library to use this new way of running tests.

I don't know how high a priority this issue is because I have yet to migrate my local tests over to the new "Virtualized Sandbox".

**Comment by code2prog** [comment]
@rmcveigh It seems that we don't need to change anything about it. 

object(stdClass)#473 (9) {
  ["alerts"]=>
  array(1) {
    [0]=>
    object(stdClass)#469 (3) {
      ["code"]=>
      string(16) "VIRTUAL.RESPONSE"
      ["message"]=>
      string(27) "This is a Virtual Response."
      ["alertType"]=>
      string(4) "NOTE"
    }
  }
